
FROM python:3.12-slim

WORKDIR /app
COPY requirements.txt .

# Instalar las dependencias requeridas
RUN pip install --no-cache-dir -r requirements.txt

COPY alfresco_audit_to_gcs.py .

CMD ["python", "alfresco_audit_to_gcs.py"]
